######################################################################
# Automatically generated by qmake (3.1) Mon May 24 17:26:43 2021
######################################################################

TEMPLATE = app
TARGET = powerdevil
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += daemon/brightnessosdwidget.h \
           daemon/chargethresholdhelper.h \
           daemon/kwinkscreenhelpereffect.h \
           daemon/powerdevil_debug.h \
           daemon/powerdevilaction.h \
           daemon/powerdevilactionconfig.h \
           daemon/powerdevilactionpool.h \
           daemon/powerdevilapp.h \
           daemon/powerdevilbackendinterface.h \
           daemon/powerdevilbrightnesslogic.h \
           daemon/powerdevilcore.h \
           daemon/powerdevilfdoconnector.h \
           daemon/powerdevilkeyboardbrightnesslogic.h \
           daemon/powerdevilpolicyagent.h \
           daemon/powerdevilpowermanagement.h \
           daemon/powerdevilprofilegenerator.h \
           daemon/powerdevilscreenbrightnesslogic.h \
           kcmodule/activities/activitypage.h \
           kcmodule/activities/activitywidget.h \
           kcmodule/common/actionconfigwidget.h \
           kcmodule/common/actioneditwidget.h \
           kcmodule/common/ErrorOverlay.h \
           kcmodule/global/GeneralPage.h \
           kcmodule/profiles/EditPage.h \
           daemon/actions/bundled/brightnesscontrol.h \
           daemon/actions/bundled/brightnesscontrolconfig.h \
           daemon/actions/bundled/dimdisplay.h \
           daemon/actions/bundled/dimdisplayconfig.h \
           daemon/actions/bundled/handlebuttonevents.h \
           daemon/actions/bundled/handlebuttoneventsconfig.h \
           daemon/actions/bundled/keyboardbrightnesscontrol.h \
           daemon/actions/bundled/keyboardbrightnesscontrolconfig.h \
           daemon/actions/bundled/runscript.h \
           daemon/actions/bundled/runscriptconfig.h \
           daemon/actions/bundled/suspendsession.h \
           daemon/actions/bundled/suspendsessionconfig.h \
           daemon/actions/bundled/wirelesspowersaving.h \
           daemon/actions/bundled/wirelesspowersavingconfig.h \
           daemon/actions/dpms/abstractdpmshelper.h \
           daemon/actions/dpms/powerdevildpmsaction.h \
           daemon/actions/dpms/powerdevildpmsactionconfig.h \
           daemon/actions/dpms/waylanddpmshelper.h \
           daemon/actions/dpms/xcbdpmshelper.h \
           daemon/backends/upower/backlighthelper.h \
           daemon/backends/upower/ddcutilbrightness.h \
           daemon/backends/upower/discretegpuhelper.h \
           daemon/backends/upower/login1suspendjob.h \
           daemon/backends/upower/powerdevilupowerbackend.h \
           daemon/backends/upower/udevqt.h \
           daemon/backends/upower/udevqt_p.h \
           daemon/backends/upower/udevqtclient.h \
           daemon/backends/upower/udevqtdevice.h \
           daemon/backends/upower/upowersuspendjob.h \
           daemon/backends/upower/xrandrbrightness.h \
           daemon/backends/upower/xrandrxcbhelper.h
FORMS += kcmodule/activities/activityWidget.ui \
         kcmodule/global/generalPage.ui \
         kcmodule/profiles/profileEditPage.ui
SOURCES += daemon/brightnessosdwidget.cpp \
           daemon/chargethresholdhelper.cpp \
           daemon/kwinkscreenhelpereffect.cpp \
           daemon/powerdevil_debug.cpp \
           daemon/powerdevilaction.cpp \
           daemon/powerdevilactionconfig.cpp \
           daemon/powerdevilactionpool.cpp \
           daemon/powerdevilapp.cpp \
           daemon/powerdevilbackendinterface.cpp \
           daemon/powerdevilbrightnesslogic.cpp \
           daemon/powerdevilcore.cpp \
           daemon/powerdevilfdoconnector.cpp \
           daemon/powerdevilkeyboardbrightnesslogic.cpp \
           daemon/powerdevilpolicyagent.cpp \
           daemon/powerdevilpowermanagement.cpp \
           daemon/powerdevilprofilegenerator.cpp \
           daemon/powerdevilscreenbrightnesslogic.cpp \
           kcmodule/activities/activitypage.cpp \
           kcmodule/activities/activitywidget.cpp \
           kcmodule/common/actionconfigwidget.cpp \
           kcmodule/common/actioneditwidget.cpp \
           kcmodule/common/ErrorOverlay.cpp \
           kcmodule/global/GeneralPage.cpp \
           kcmodule/profiles/EditPage.cpp \
           daemon/actions/bundled/brightnesscontrol.cpp \
           daemon/actions/bundled/brightnesscontrolconfig.cpp \
           daemon/actions/bundled/dimdisplay.cpp \
           daemon/actions/bundled/dimdisplayconfig.cpp \
           daemon/actions/bundled/handlebuttonevents.cpp \
           daemon/actions/bundled/handlebuttoneventsconfig.cpp \
           daemon/actions/bundled/keyboardbrightnesscontrol.cpp \
           daemon/actions/bundled/keyboardbrightnesscontrolconfig.cpp \
           daemon/actions/bundled/runscript.cpp \
           daemon/actions/bundled/runscriptconfig.cpp \
           daemon/actions/bundled/suspendsession.cpp \
           daemon/actions/bundled/suspendsessionconfig.cpp \
           daemon/actions/bundled/wirelesspowersaving.cpp \
           daemon/actions/bundled/wirelesspowersavingconfig.cpp \
           daemon/actions/dpms/abstractdpmshelper.cpp \
           daemon/actions/dpms/powerdevildpmsaction.cpp \
           daemon/actions/dpms/powerdevildpmsactionconfig.cpp \
           daemon/actions/dpms/waylanddpmshelper.cpp \
           daemon/actions/dpms/xcbdpmshelper.cpp \
           daemon/backends/upower/backlighthelper.cpp \
           daemon/backends/upower/ddcutilbrightness.cpp \
           daemon/backends/upower/discretegpuhelper.cpp \
           daemon/backends/upower/login1suspendjob.cpp \
           daemon/backends/upower/powerdevilupowerbackend.cpp \
           daemon/backends/upower/udevqtclient.cpp \
           daemon/backends/upower/udevqtdevice.cpp \
           daemon/backends/upower/upowersuspendjob.cpp \
           daemon/backends/upower/xrandrbrightness.cpp \
           daemon/backends/upower/xrandrxcbhelper.cpp
